from typing import Generator

import pytest
from fastapi.testclient import TestClient
from sqlalchemy.pool import StaticPool
from sqlmodel import SQLModel, Session, create_engine

from core.database import get_session
from main import app


@pytest.fixture
def client() -> Generator[TestClient, None, None]:
    test_engine = create_engine(
        "sqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    SQLModel.metadata.create_all(test_engine)

    def override_get_session() -> Generator[Session, None, None]:
        with Session(test_engine) as session:
            yield session

    app.dependency_overrides[get_session] = override_get_session
    test_client = TestClient(app)
    try:
        yield test_client
    finally:
        app.dependency_overrides.clear()


def create_model(client: TestClient, name: str = "Test Model") -> dict:
    response = client.post(
        "/api/models",
        json={
            "name": name,
            "version": "1.0",
            "description": "Model for tests",
            "status": "draft",
            "repo_link": "https://github.com/example/repo",
        },
    )
    assert response.status_code == 200
    return response.json()


def test_health_metrics_endpoint(client: TestClient) -> None:
    response = client.get("/dashboard/metrics")
    assert response.status_code == 200
    payload = response.json()
    assert payload["total_models"] == 0
    assert "high_risk_models" in payload
    assert "controls_verified" in payload


def test_create_and_list_models(client: TestClient) -> None:
    created = create_model(client, name="Lifecycle Model")
    assert created["name"] == "Lifecycle Model"
    assert created["status"] == "draft"

    list_response = client.get("/api/models")
    assert list_response.status_code == 200
    models = list_response.json()
    assert len(models) == 1
    assert models[0]["name"] == "Lifecycle Model"


def test_search_models(client: TestClient) -> None:
    create_model(client, name="Fraud Detector")
    create_model(client, name="Pricing Predictor")

    response = client.get("/api/models/search", params={"q": "Fraud"})
    assert response.status_code == 200
    results = response.json()
    assert len(results) == 1
    assert results[0]["name"] == "Fraud Detector"


def test_get_model_not_found(client: TestClient) -> None:
    response = client.get("/api/models/9999")
    assert response.status_code == 404


def test_analyze_model_with_stubbed_ai(client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    created = create_model(client, name="Analysis Model")
    model_id = created["id"]

    from app.services import groq_ai_engine as groq_module

    def fake_map_to_osfi_controls(_model_data: dict) -> list[dict]:
        return [
            {
                "osfi_control": "Model validation and testing requirements",
                "ai_rationale": "Test rationale",
                "status": "Proposed",
            }
        ]

    def fake_generate_model_documentation(_model_data: dict) -> str:
        return "# Test Documentation\n\nGenerated by stub."

    monkeypatch.setattr(groq_module.groq_ai_engine, "map_to_osfi_controls", fake_map_to_osfi_controls)
    monkeypatch.setattr(
        groq_module.groq_ai_engine,
        "generate_model_documentation",
        fake_generate_model_documentation,
    )

    response = client.post(f"/api/models/{model_id}/analyze")
    assert response.status_code == 200
    payload = response.json()
    assert payload["documentation"].startswith("# Test Documentation")
    assert len(payload["controls"]) == 1
    assert payload["controls"][0]["status"] == "Proposed"


def test_auth_context_endpoint(client: TestClient) -> None:
    response = client.get(
        "/api/auth/me",
        headers={"x-user-id": "risk-user-1", "x-user-role": "risk_officer"},
    )
    assert response.status_code == 200
    payload = response.json()
    assert payload == {"user_id": "risk-user-1", "role": "risk_officer"}


def test_auth_context_invalid_role_returns_400(client: TestClient) -> None:
    response = client.get("/api/auth/me", headers={"x-user-role": "not_a_role"})
    assert response.status_code == 400
